### ISSUE TITLE
threads option

### ISSUE THREAD

**Issue by backd00r101** [Damian89/xssfinder#7]
hello damian, 
thanks for the awesome tool : )
i suggest implementing threads as it will be really awesome and way faster
Thanks!

**Comment by Damian89** [comment]
I had that option in an early version but it turned out that a versio which just uses a lot of params (default 75) per request is much more reliable and also fast ( testing all params results in ~35 requests). Most sites respond super fast so a check takes < 1 min. Sites which are super slow are those where you cant use threading because it will fail with blocked requests or long waiting times. To be honest I dont think I will implement it in the near future - a valid point may be a much bigger wordlist, but thats currently not the case ;)
